### ISSUE TITLE
Not working with React 15.5

### ISSUE THREAD

**Issue by Ninjami-Juho** [iqnivek/react-circular-progressbar#18]
I get this error With React 15.5.4 and React-dom 15.5.4:
`Warning: Failed prop type: Calling PropTypes validators directly is not supported by the 'prop-types' package. Use PropTypes.checkPropTypes() to call them.`

Looks like react-circular-progressbar needs to use the prop-types library.
[Don't Call PropTypes Warning](https://facebook.github.io/react/warnings/dont-call-proptypes.html)

**Comment by AlexanderKosianchuk** [comment]
Actually  warning, not error. And i think if not working on React 15.5, not because this warning. But it really wont work on react 16 

https://github.com/facebook/prop-types/blob/master/README.md#difference-from-reactproptypes-dont-call-validator-functions

"If you temporarily need the old behavior, you can keep using React.PropTypes until React 16".

But still it would be nice to fix it

**Comment by AlexanderKosianchuk** [comment]
Looking into 

https://github.com/iqnivek/react-circular-progressbar/blob/master/src/index.jsx

and

https://github.com/iqnivek/react-circular-progressbar/commit/fd6741a6379dec2fb79512cbb2dfd3b90c94567b

There was
import React, { PropTypes } from 'react'; 
but it was fixed 
import PropTypes from 'prop-types';

So it is just necessary to make new release, to apply changes and become them avaliable on npmjs for сommunity.
Kevin Qi, please do it.

**Comment by iqnivek** [comment]
hi all - sorry about the delay in replying, I'd been out on vacation and didn't have internet access. 

@AlexanderKosianchuk yup, I did commit a fix for the prop-types import warning, and thought I'd released it in v0.1.4. However, I tested it out on react 15.6 and it's still showing up, so either the commit wasn't published properly, or there's another change needed besides `import PropTypes from 'prop-types';`. I haven't had much time to look at it, but I'm hoping to fix this shortly. Thanks for bearing with me.

**Comment by iqnivek** [comment]
this was a bit of a pain to track down - react-calendar-heatmap was using prop-types correctly, but it turns out there was [an issue with prop-types itself](https://github.com/facebook/prop-types/issues/38), which caused the warning to happen here, and in a whole lot of other react libraries too. The fix was just to upgrade to a newer version of prop-types, v15.5.10. This is now released in react-circular-progressbar 0.1.5!
